services:
  telgpt:
    build: ./src
    container_name: telgpt
    restart: always
    environment:
      - TEL_GPT_DISCORD_TOKEN=${TEL_GPT_DISCORD_TOKEN}
      - TEL_GPT_OPEN_AI_TOKEN=${TEL_GPT_OPEN_AI_TOKEN}
      - TEL_GPT_DEEPL_TOKEN=${TEL_GPT_DEEPL_TOKEN}
      - TEL_GPT_GEMINI_TOKEN=${TEL_GPT_GEMINI_TOKEN}
      - TEL_GPT_CLAUDE_TOKEN=${TEL_GPT_CLAUDE_TOKEN}
      - TEL_GPT_STABILITY_TOKEN=${TEL_GPT_STABILITY_TOKEN}
      - TEL_GPT_STATUS_CHANNEL_ID=${TEL_GPT_STATUS_CHANNEL_ID}
      - GITHUB_ISSUE_PAT=${GITHUB_ISSUE_PAT}
