services:
  telgpt:
    build: ./src
    container_name: telgpt
    environment:
      - TEL_GPT_DISCORD_TOKEN=${TEL_GPT_DISCORD_TOKEN}
      - TEL_GPT_OPEN_AI_TOKEN=${TEL_GPT_OPEN_AI_TOKEN}
      - TEL_GPT_DEEPL_TOKEN=${TEL_GPT_DEEPL_TOKEN}
      - TEL_GPT_GEMINI_TOKEN=${TEL_GPT_GEMINI_TOKEN}
      - GITHUB_ISSUE_PAT=${GITHUB_ISSUE_PAT}
