version: "3.8"

services:
  telgpt:
    build: ./src
    container_name: telgpt
    environment:
      - TEL_GPT_DISCORD_TOKEN=
      - TEL_GPT_OPEN_AI_TOKEN=
      - TEL_GPT_DEEPL_TOKEN=
      - GITHUB_ISSUE_PAT=
